FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# VGDB

Video Game Database for UT Austin SWE project IDB

## Games [/games]

### List Games [GET]

+ Response 200 (application/json)

        [
            {
                "id": "123",
                "title": "Overwatch",
                "releaseDate": "2015",
                "description": "...",
                "platform": [
                    "PC",
                    "PS4",
                    "XBOX1"
                ],
                "image": "https://....com/image.png",
                "avgRating": "8.2",
                "numRatings": "1234567",
                "characters": [
                    "char_id_1",
                    "char_id_2"
                ]
                
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }